# Generated by Django 3.2.10 on 2022-03-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0006_auto_20220307_1708"),
    ]

    operations = [
        migrations.AddField(
            model_name="celebrity",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
