# Generated by Django 3.2.10 on 2022-03-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0007_auto_20220317_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celebrity",
            name="first_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="celebrity",
            name="last_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
    ]
