# Generated by Django 3.2.10 on 2022-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0008_auto_20220317_1434"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celebrity",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
