# Generated by Django 3.2.10 on 2022-03-29 14:19

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0009_alter_celebrity_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celebrity",
            name="country",
            field=django_countries.fields.CountryField(default="SA", max_length=2),
        ),
    ]
